/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSpendingIndexRouteImport } from './routes/_authenticated/spending/index'
import { Route as AuthenticatedSpendingTypeIndexRouteImport } from './routes/_authenticated/spending-type/index'
import { Route as AuthenticatedResidentsIndexRouteImport } from './routes/_authenticated/residents/index'
import { Route as AuthenticatedHousesIndexRouteImport } from './routes/_authenticated/houses/index'
import { Route as AuthenticatedHousePaymentsIndexRouteImport } from './routes/_authenticated/house-payments/index'
import { Route as AuthenticatedHistoryIndexRouteImport } from './routes/_authenticated/history/index'
import { Route as AuthenticatedDueTypeIndexRouteImport } from './routes/_authenticated/due-type/index'
import { Route as AuthenticatedDuePaymentIndexRouteImport } from './routes/_authenticated/due-payment/index'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSpendingIndexRoute =
  AuthenticatedSpendingIndexRouteImport.update({
    id: '/spending/',
    path: '/spending/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSpendingTypeIndexRoute =
  AuthenticatedSpendingTypeIndexRouteImport.update({
    id: '/spending-type/',
    path: '/spending-type/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResidentsIndexRoute =
  AuthenticatedResidentsIndexRouteImport.update({
    id: '/residents/',
    path: '/residents/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHousesIndexRoute =
  AuthenticatedHousesIndexRouteImport.update({
    id: '/houses/',
    path: '/houses/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHousePaymentsIndexRoute =
  AuthenticatedHousePaymentsIndexRouteImport.update({
    id: '/house-payments/',
    path: '/house-payments/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHistoryIndexRoute =
  AuthenticatedHistoryIndexRouteImport.update({
    id: '/history/',
    path: '/history/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDueTypeIndexRoute =
  AuthenticatedDueTypeIndexRouteImport.update({
    id: '/due-type/',
    path: '/due-type/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDuePaymentIndexRoute =
  AuthenticatedDuePaymentIndexRouteImport.update({
    id: '/due-payment/',
    path: '/due-payment/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/due-payment/': typeof AuthenticatedDuePaymentIndexRoute
  '/due-type/': typeof AuthenticatedDueTypeIndexRoute
  '/history/': typeof AuthenticatedHistoryIndexRoute
  '/house-payments/': typeof AuthenticatedHousePaymentsIndexRoute
  '/houses/': typeof AuthenticatedHousesIndexRoute
  '/residents/': typeof AuthenticatedResidentsIndexRoute
  '/spending-type/': typeof AuthenticatedSpendingTypeIndexRoute
  '/spending/': typeof AuthenticatedSpendingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/due-payment': typeof AuthenticatedDuePaymentIndexRoute
  '/due-type': typeof AuthenticatedDueTypeIndexRoute
  '/history': typeof AuthenticatedHistoryIndexRoute
  '/house-payments': typeof AuthenticatedHousePaymentsIndexRoute
  '/houses': typeof AuthenticatedHousesIndexRoute
  '/residents': typeof AuthenticatedResidentsIndexRoute
  '/spending-type': typeof AuthenticatedSpendingTypeIndexRoute
  '/spending': typeof AuthenticatedSpendingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/due-payment/': typeof AuthenticatedDuePaymentIndexRoute
  '/_authenticated/due-type/': typeof AuthenticatedDueTypeIndexRoute
  '/_authenticated/history/': typeof AuthenticatedHistoryIndexRoute
  '/_authenticated/house-payments/': typeof AuthenticatedHousePaymentsIndexRoute
  '/_authenticated/houses/': typeof AuthenticatedHousesIndexRoute
  '/_authenticated/residents/': typeof AuthenticatedResidentsIndexRoute
  '/_authenticated/spending-type/': typeof AuthenticatedSpendingTypeIndexRoute
  '/_authenticated/spending/': typeof AuthenticatedSpendingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/due-payment/'
    | '/due-type/'
    | '/history/'
    | '/house-payments/'
    | '/houses/'
    | '/residents/'
    | '/spending-type/'
    | '/spending/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/due-payment'
    | '/due-type'
    | '/history'
    | '/house-payments'
    | '/houses'
    | '/residents'
    | '/spending-type'
    | '/spending'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/_authenticated/dashboard'
    | '/_authenticated/due-payment/'
    | '/_authenticated/due-type/'
    | '/_authenticated/history/'
    | '/_authenticated/house-payments/'
    | '/_authenticated/houses/'
    | '/_authenticated/residents/'
    | '/_authenticated/spending-type/'
    | '/_authenticated/spending/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/spending/': {
      id: '/_authenticated/spending/'
      path: '/spending'
      fullPath: '/spending/'
      preLoaderRoute: typeof AuthenticatedSpendingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/spending-type/': {
      id: '/_authenticated/spending-type/'
      path: '/spending-type'
      fullPath: '/spending-type/'
      preLoaderRoute: typeof AuthenticatedSpendingTypeIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/residents/': {
      id: '/_authenticated/residents/'
      path: '/residents'
      fullPath: '/residents/'
      preLoaderRoute: typeof AuthenticatedResidentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/houses/': {
      id: '/_authenticated/houses/'
      path: '/houses'
      fullPath: '/houses/'
      preLoaderRoute: typeof AuthenticatedHousesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/house-payments/': {
      id: '/_authenticated/house-payments/'
      path: '/house-payments'
      fullPath: '/house-payments/'
      preLoaderRoute: typeof AuthenticatedHousePaymentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history/': {
      id: '/_authenticated/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof AuthenticatedHistoryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/due-type/': {
      id: '/_authenticated/due-type/'
      path: '/due-type'
      fullPath: '/due-type/'
      preLoaderRoute: typeof AuthenticatedDueTypeIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/due-payment/': {
      id: '/_authenticated/due-payment/'
      path: '/due-payment'
      fullPath: '/due-payment/'
      preLoaderRoute: typeof AuthenticatedDuePaymentIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDuePaymentIndexRoute: typeof AuthenticatedDuePaymentIndexRoute
  AuthenticatedDueTypeIndexRoute: typeof AuthenticatedDueTypeIndexRoute
  AuthenticatedHistoryIndexRoute: typeof AuthenticatedHistoryIndexRoute
  AuthenticatedHousePaymentsIndexRoute: typeof AuthenticatedHousePaymentsIndexRoute
  AuthenticatedHousesIndexRoute: typeof AuthenticatedHousesIndexRoute
  AuthenticatedResidentsIndexRoute: typeof AuthenticatedResidentsIndexRoute
  AuthenticatedSpendingTypeIndexRoute: typeof AuthenticatedSpendingTypeIndexRoute
  AuthenticatedSpendingIndexRoute: typeof AuthenticatedSpendingIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDuePaymentIndexRoute: AuthenticatedDuePaymentIndexRoute,
  AuthenticatedDueTypeIndexRoute: AuthenticatedDueTypeIndexRoute,
  AuthenticatedHistoryIndexRoute: AuthenticatedHistoryIndexRoute,
  AuthenticatedHousePaymentsIndexRoute: AuthenticatedHousePaymentsIndexRoute,
  AuthenticatedHousesIndexRoute: AuthenticatedHousesIndexRoute,
  AuthenticatedResidentsIndexRoute: AuthenticatedResidentsIndexRoute,
  AuthenticatedSpendingTypeIndexRoute: AuthenticatedSpendingTypeIndexRoute,
  AuthenticatedSpendingIndexRoute: AuthenticatedSpendingIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
